// para usar este codigo deben poner algo como:
// import Pic from './public/pic/Pic.jsx';
// y luego usarla como src: Pic.image1 para mostrar la primera foto por ejemplo

const Pic = {
    image1: new URL('./6153098.png', import.meta.url).href,
    image2: new URL('./c19561915454efb7bd7a9d8a2461f881.jpg', import.meta.url).href,
    image3: new URL('./Captura de pantalla 2024-04-28 190135.jpg', import.meta.url).href,
    image4: new URL('./Designer (7).png', import.meta.url).href,
    image5: new URL('./Designer (8).png', import.meta.url).href,
    image6: new URL('./Designer (9).png', import.meta.url).href,
    image7: new URL('./Designer (16) 1.png', import.meta.url).href,
    image8: new URL('./Designer (37).jpeg', import.meta.url).href,
    image9: new URL('./Designer (38).jpeg', import.meta.url).href,
    image10: new URL('./Designer (39).jpeg', import.meta.url).href,
    image11: new URL('./Designer (40).jpeg', import.meta.url).href,
    image12: new URL('./Designer (41).jpeg', import.meta.url).href,
    image13: new URL('./Designer (42) 1.png', import.meta.url).href,
    image14: new URL('./Designer (42).jpeg', import.meta.url).href,
    image15: new URL('./Designer (43).jpeg', import.meta.url).href,
    image16: new URL('./Designer (44).jpeg', import.meta.url).href,
    image17: new URL('./Designer (45).jpeg', import.meta.url).href,
    image18: new URL('./Designer (46).jpeg', import.meta.url).href,
    image19: new URL('./Designer (47).jpeg', import.meta.url).href,
    image20: new URL('./Designer (48).jpeg', import.meta.url).href,
    image21: new URL('./Designer (49).jpeg', import.meta.url).href,
    image22: new URL('./Designer (50).jpeg', import.meta.url).href,
    image23: new URL('./Designer (51).jpeg', import.meta.url).href,
    image24: new URL('./Designer (52).jpeg', import.meta.url).href,
    image25: new URL('./Designer (53).jpeg', import.meta.url).href,
    image26: new URL('./Designer (54).jpeg', import.meta.url).href,
    image27: new URL('./Designer (55).jpeg', import.meta.url).href,
    image28: new URL('./Designer (56).jpeg', import.meta.url).href,
    image29: new URL('./Designer (57).jpeg', import.meta.url).href,
    image30: new URL('./Designer (58).jpeg', import.meta.url).href,
    image31: new URL('./Designer (59).jpeg', import.meta.url).href,
    image32: new URL('./Designer (60).jpeg', import.meta.url).href,
    image33: new URL('./Designer (61).jpeg', import.meta.url).href,
    image34: new URL('./Designer (62).jpeg', import.meta.url).href,
    image35: new URL('./Designer (63).jpeg', import.meta.url).href,
    image36: new URL('./Designer (64).jpeg', import.meta.url).href,
    image37: new URL('./Designer (65).jpeg', import.meta.url).href,
    image38: new URL('./Designer (67) (1).jpeg', import.meta.url).href,
    image39: new URL('./Designer (84).jpeg', import.meta.url).href,
    image40: new URL('./Designer (85).jpeg', import.meta.url).href,
    image41: new URL('./Designer (87).jpeg', import.meta.url).href,
    image42: new URL('./Designer (90).jpeg', import.meta.url).href,
    image43: new URL('./Designer (91).jpeg', import.meta.url).href,
    image44: new URL('./Diseño sin título 1.png', import.meta.url).href,
    image45: new URL('./fondoCómomesiento.jpeg', import.meta.url).href,
    image46: new URL('./fondoCómomesiento1.jpeg', import.meta.url).href,
    image47: new URL('./Frame 427318921.png', import.meta.url).href,
    image48: new URL('./inteligencias-múltiples 1.png', import.meta.url).href,
    image49: new URL('./mentaloasislogo.png', import.meta.url).href,
    image50: new URL('./pixelcut.png', import.meta.url).href,
    image51: new URL('./unnamed.jpg', import.meta.url).href,
    image52: new URL('./WhatsApp Image 2024-04-28 at 16.52.04 (3).jpeg', import.meta.url).href,
    image53: new URL('./WhatsApp Image 2024-04-28 at 16.52.05 (2).jpeg', import.meta.url).href,
    image54: new URL('./WhatsApp Image 2024-04-28 at 16.52.05 (3).jpeg', import.meta.url).href,
    image55: new URL('./WhatsApp Image 2024-04-28 at 16.52.05 (4).jpeg', import.meta.url).href,
    image56: new URL('./WhatsApp Image 2024-04-28 at 16.52.06 (1).jpeg', import.meta.url).href,
    image57: new URL('./WhatsApp Image 2024-04-28 at 16.52.06.jpeg', import.meta.url).href,
    image58: new URL('./WhatsApp Image 2024-04-28 at 16.52.07 (2).jpeg', import.meta.url).href,
    image59: new URL('./WhatsApp Image 2024-04-28 at 16.52.07.jpeg', import.meta.url).href,
    image60: new URL('./WhatsApp Image 2024-04-28 at 16.52.08 (2).jpeg', import.meta.url).href,
    image61: new URL('./WhatsApp Image 2024-05-03 at 09.15.49 (1).jpeg', import.meta.url).href,
    image62: new URL('./WhatsApp_Image_2024-04-18_at_10.15 2.png', import.meta.url).href,
}

export default Pic;